apiVersion: v1
kind: Pod
metadata:
  name: sayeed
  labels:
    name: app
    project: infinity
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - name: nginx-port
          containerPort: 80

