---
apiVersion: v1
kind: Pod
metadata:
  name: vproapp
  labels:
    app: vproapp
    project: vprofile
spec:
  containers:
    - name: appcontainer
      image: imranvisualpath/freshtomapp:v7
      ports:
        - name: vproapp-port
          containerPort: 8080

